# Generated by Django 2.0.3 on 2018-04-19 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgnization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgnization.CityDict', verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='desc',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='讲师介绍'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgnization.CourseOrg', verbose_name='所属机构'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='points',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='教学特点'),
        ),
    ]
