# Generated by Django 2.0.3 on 2018-04-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': '章(Chapter)', 'verbose_name_plural': '章(Chapter)'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '节(Lesson)', 'verbose_name_plural': '节(Lesson)'},
        ),
    ]
