# Generated by Django 2.0.3 on 2018-04-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgnization', '0002_auto_20180419_2056'),
        ('courses', '0002_auto_20180419_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgnization.Teacher', verbose_name='授课教师'),
        ),
    ]
