# Generated by Django 2.0.3 on 2018-04-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180419_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_desc',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='章节介绍'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='章节标题'),
        ),
    ]
