# Generated by Django 2.0.3 on 2018-04-20 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180420_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_time_duration',
            field=models.CharField(max_length=10, verbose_name='视频时长(xx时xx分xx秒)'),
        ),
    ]
