# Generated by Django 2.0.3 on 2018-04-21 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180420_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='类别名称')),
                ('is_root', models.BooleanField(default=False, verbose_name='是否为根节点')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Type', verbose_name='所属父类别')),
            ],
            options={
                'verbose_name_plural': '课程类别',
                'verbose_name': '课程类别',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True, default=0, max_length=10, null=True, verbose_name='课程价格'),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Type', verbose_name='所属类别'),
        ),
    ]
